### PR TITLE
Add littlefoot.js options as block options

### PR DESCRIPTION
**Pull request by s3rgiosan**
**Default state / Disabled state**

Screenshot 2024-01-30 at 00 02 00

**Enabled state**

Screenshot 2024-01-30 at 00 02 07

### CODE REVIEW

**Review by goblindegook — APPROVED** [review]

**Comment by xipasduarte** [comment]
Only note I'd have is why do we need a switch to enable the options. They exist, and this is a collapse element. Is this a pattern of some kind in the new editor?

**Comment by goblindegook** [comment]
The way I understood it is that "Enable" is for having footnotes (or not) on that specific document. Right?

**Comment by s3rgiosan** [comment]
"Enable" is to enable littlefoot on that specific document. The plugin does not enable littlefoot globally.

**Comment by s3rgiosan** [comment]
I'll revert this logic and remove the Enable toggle.

**Pull request merged**
